### ISSUE TITLE
getSoftButtonCapabilities methods for RegisterAppInterfaceResponse and SetDisplayLayoutResponse need enhancements

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_android#148]
Currently SDL core (and Sync Gen3) will only return a single SoftButtonCapabilities object in both the RegisterAppInterfaceResponse and SetDisplayLayoutResponse, however both of the SoftButtonCapabilities types in these responses have been specced to be lists (as returned by previous Sync Gen 1.1 hardware).

To protect for existing and future hardware, we need to enhance the getSoftButtonCapabilities methods linked below to check 
`parameters.get(KEY_SOFT_BUTTON_CAPABILITIES)` and return a new List<SoftButtonCapabilities> even when only a single object is returned by core.

https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/proxy/rpc/RegisterAppInterfaceResponse.java#L234-251

https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/proxy/rpc/SetDisplayLayoutResponse.java#L88-105

**Comment by mikeburke106** [comment]
Adding this to #90 as well.

**Comment by mikeburke106** [comment]
@mrapitis Do you know why Sync 3 was updated to go against the spec when it was working properly already?

**Comment by mikeburke106** [comment]
Also, is it too late to fix issue this core-side so we don't have to add another corner-case to the mobile libraries?

**Comment by mrapitis** [comment]
Unfortunately its too late to fix this core side.  This was also a bug in older versions on Gen 3 and sdl core software, however somehow this specific case fell through the cracks.

**Comment by mikeburke106** [comment]
Thanks for bringing up this issue, we need to understand more of these situations so we can account for them moving forward.

I still don't understand how we could let this happen if it was working correctly on previous versions of core... we obviously need more unit tests and regression testing core-side.  Putting out fires at the last minute is no fun for anyone, so let's start being proactive and take steps to make sure this can't happen again in the future.

We, collectively, need to make more of an effort to get hardware partners to follow the spec because abusing mobile libraries like this just because they're easier to update is going to get unmanageable fast - especially when we get other OEMs on board.  We have arguably already reached a point where all these corner cases are going to be impossible to manage in the future.

If we keep piling corner cases into the mobile libraries, something will eventually fall through the cracks and will potentially lead to bad end-user experiences for all OEMs who use SDL.  These corner cases make it practically impossible to maintain a good software design and introduce bloat to our libraries - not to mention infecting the libraries with code that is only useful to one specific OEM.

**Comment by justinjdickow** [comment]
Need to confirm this was fixed module side
