### ISSUE TITLE
USB AOA write Error

### ISSUE THREAD

**Issue by yifili09** [smartdevicelink/sdl_android#197]
There is an issue about App can't  get register after physical re-connecting USB cable.

Mobile OS did notify the User to select one App for launching via AOA protocol and app get register on HeadUnit for the 1st time USB cable connected.
Then disconnect , keep the App alive and re-connect the USB cable, mobile OS did notify the User again meanwhile the mobile did switch to Accessory mode but can't made Hand Shake via OutPutStream write function.
Log was attached as reference. Thanks!

![usbtransport_connect](https://cloud.githubusercontent.com/assets/1016943/7697391/ff985544-fe39-11e4-9ebb-67b589ac84c1.png)
![aoa_write_log_](https://cloud.githubusercontent.com/assets/1016943/7697392/02754952-fe3a-11e4-9038-13d9f7990fb7.png)

The Hand Shake has been transmitted successfully for the 1st time USB connected.
![have_permission_](https://cloud.githubusercontent.com/assets/1016943/7698103/165cabc6-fe40-11e4-87b8-5020fe7be139.png)

**Comment by mrapitis** [comment]
The following discussion may be pertinent:

https://code.google.com/p/android/issues/detail?id=20545

**Comment by khburdette** [comment]
After doing some testing, I believe this is an app's intent issue. What I mean by this, is that the intent that listens for the AOA connection is calling the main activity every time. This might work for the first connection because the transport hasn't initialized yet, but, with any additional connections during the lifecycle of the app, the new activity will spin up another proxy and be using a transport object that isn't actually the transport object that made the connection, and therefor error when writing to the output buffer.

**Comment by yifili09** [comment]
@khburdette  Thanks!  The issue has been fixed and could be closed.
