### ISSUE TITLE
Add PLAY_PAUSE to ButtonName enum

### ISSUE THREAD

**Issue by justinjdickow** [smartdevicelink/sdl_android#228]

**Comment by kshala-ford** [comment]
@joeygrover  any update to the PLAY_PAUSE feature? Anyhting that need to be done beforehand?

**Comment by joeygrover** [comment]
Hi @kshala-ford,

In the future, please try not to post questions about a global SDL feature in multiple repos, this would be better as a question in Slack.

The PLAY_PAUSE enum needs to be added to the RPC spec at an agreed upon version. Due to old systems using OK as the PLAY_PAUSE functionality, we need to ensure that when developers subscribe to only PLAY_PAUSE that on older systems the library can subscribe them to OK. Then when an OK is received, translate it to a PLAY_PAUSE. It would be best added once the SDLC has a proper versioning system in place for the RPC spec. The roadmap has this versioning process in place this quarter.

**Comment by BrettyWhite** [comment]
Closed with #864
