### ISSUE TITLE
SDL app that restarts is not reconnecting to already running/connected router.

### ISSUE THREAD

**Issue by jthrun** [smartdevicelink/sdl_android#328]
I think this one is similar to #307 in that it happens when there are more than one routers running and the first router found in the list of running services is not the router connected to SDLCore.

Make sure there are multiple SDL apps installed.

Connect to SDLCore on the HU using custom UUID through the companion app that matches this UUID.
Select one SDL app that is connected to SDLCore through this companion app's router.  Display this app in HMI and then kill (force-stop, crash, etc.) the app.  Restart the app.  At this point it will not reconnect to the companion app's router because another router, which is not connected to SDLCore, will be found first in the running services list from the Android system.

Note that the app connects to the correct router the first time because of changes made that corrected #307.  It is only after the app has died and been restarted that it will not find the correct router to reconnect to.

**Comment by joeygrover** [comment]
I can see the logic around why this is happening. This goes back to assumption that only one router should be running at a time. Having a custom UUID breaks the normal flow, so I'll have to do some research into how to accommodate it in this scenario.

**Comment by joeygrover** [comment]
I have two ideas on how to solve this.

1. Gather all router services in an array and iterate through them, connecting to one at a time to find their connected status. If one is connected to hardware, set that as the router service to connect to. This method is more processor intensive and would take time. 
2. In the router service, check to see if an app as the permission to use sticky intents and send out a sticky intent instead of a normal intent when notifying apps that the router service is connected. The client apps could check to see if a sticky intent is around first, if not, go through the process as it stands today. This is more memory intensive, but it wouldn't store much.

I'm leaning towards the second option as it doesn't break normal flow much and if other apps have the permission to use sticky intents we can reduce the time it takes to connect to a router service.

**Comment by jthrun** [comment]
I've read there are some concerns with sticky intents.  One concern is that apparently any app can modify a stick intent.  Another is that it may stick around for a long time, so a router that looses connection probably needs to remove the intent on that event.  The first concern is probably the most worrisome, but maybe it is acceptable in our case.

**Comment by joeygrover** [comment]
Yea the sticky intent would stay around until the caller removed it or it is modified over I believe. However, that is a good point, probably not worth much if an app can just overwrite it. So I can move towards option 1 for now unless any other idea comes up.

**Comment by jthrun** [comment]
I did a version of option 1 for our internal test apps.  I couldn't think of anything else at the time.

**Comment by jthrun** [comment]
Has this been added to the documentation?  I saw that it was added to the sample HelloSdlAndroid app.  If it isn't yet added to the docs can it be?
