### ISSUE TITLE
Exported service does not require permission for SdlRouterService

### ISSUE THREAD

**Issue by joeygrover** [smartdevicelink/sdl_android#352]
When developers set the exported flag to true in their manifest declaration of the SdlRouterService Lint throws a warning "Exported service does not require permission"

**Comment by brettywhite** [comment]
This Lint can be suppressed by the developer adding `tools:ignore="ExportedService"` to their service declaration in their manifest. This warning is because we do not supply an intent-filter for the exported service. The documentation and example app have been updated to include this and have a better explanation. The 2 pull requests are listed below. 

https://github.com/smartdevicelink/hello_sdl_android/pull/26
https://github.com/smartdevicelink/sdl_android_guides/pull/69
