### ISSUE TITLE
RTL support and Allow backup are forced by smartdevicelink

### ISSUE THREAD

**Issue by valeriia-shchukina** [smartdevicelink/sdl_android#368]
Manifest properties "allowBackup" and "supportsRtl" are usually set to false by default, but seems like they are set to true in smartdevicelink.

**Comment by brettywhite** [comment]
SDL supports rtl languages, so that being set to true is on purpose. It still will work with non-rtl languages if it is set to `false` in your app's manifest. 

As for `allowBackup` do you see it in documentation that it has to be set to `true`? I just built an application with it to false and got no errors or warnings. I couldn't find that documentation. Please let me know.

If this was an issue on a previous version and is no longer an issue, please close the issue.

**Comment by brettywhite** [comment]
Closing as I believe this was a problem in pre-android studio releases and is no longer an issue
