### ISSUE TITLE
Stream packetizer buffer size should be consistent with MTU

### ISSUE THREAD

**Issue by henry-fan** [smartdevicelink/sdl_android#418]
https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/streaming/StreamPacketizer.java#L17

Buffer size should be set to MTU size dynamically. See relevant issue #36

**Comment by tpulatha** [comment]
Maybe some more comment here: We seem to have forgotten to set the packetizer size to be dynamically changed based on the MTU size. This should negatively impact video streaming performance...

**Comment by joeygrover** [comment]
This was a known issue actually. The reason it was hard coded/different than the overall MTU was due to an OEM specific implementation that had trouble dealing with the larger packet sizes when using encryption. (I believe @mrapitis can give more info if needed) I already have code that allows the packetizer buffer to be the 1024 if encrypted and the dynamic MTU otherwise. This can get added to the 4.3.0 release as I do see it as a bug.

**Comment by mrapitis** [comment]
@joeygrover is right, the 1024 byte was set because of an oem specific hardware limitation when processing encrypted data.  As a side note from a video service perspective, increasing the value does not seem to provide much of a performance boost as the device encoder is still the limiting factor (and bottleneck).

**Comment by joeygrover** [comment]
It does help on some systems. The encoder is definitely the current bottleneck, however, if we somehow fix that then this MTU size issue will become the new bottleneck.

**Comment by chenbd** [comment]
Hi, this is Baodong from MXNavi.
About video streaming performance, i did not check the latest sdl_android source, but i guess some point can be considered:
1, avoid using pipe Input/Output stream,  directly get video data from app side.(need new interface)
2, fit video data to MTU size and send every video data through single protocol message.
3,when processing video data, avoid data copy as much as possible.

**Comment by joeygrover** [comment]
Should StreamRPCPacketizer also be changed? It uses an incredibly large buffer size in comparison.

**Comment by mrapitis** [comment]
Seems like it should be changed to a more realistic value as well.

**Comment by joeygrover** [comment]
Ok, I think the change should happen to the AbstractPacketizer class then. Have that class obtain the MTU and set it as the buffer size. The StreamPacketizer can check for encryption and set a new size.

**Comment by joeygrover** [comment]
Fixed with #430
